return {
  "stevearc/conform.nvim",
  opts = {
    format_on_save = {
      lsp_fallback = true,
      timeout_ms = 1000,
    },
    formatters_by_ft = {
      lua = { "stylua" },
      python = { "black" },
      javascript = { "prettier" },
      typescript = { "prettier" },
      html = { "prettier" },
      css = { "prettier" },
      json = { "prettier" },
      yaml = { "prettier" },
      sh = { "shfmt" },
      sql = { "sqlfluff" },
      mysql = { "sqlfluff" },
      postgres = { "sqlfluff" },
      go = { "gofmt" },
      rust = { "rustfmt" },
      c = { "clang_format" },
      cpp = { "clang_format" },
      markdown = { "prettier" },
      vue = { "prettier" },
      svelte = { "prettier" },
      php = { "php_cs_fixer" },
      java = { "google_java_format" },
      ruby = { "rubocop" },
      toml = { "taplo" },
      xml = { "xmlformat" },
      dockerfile = { "hadolint" },
    },
  },
}
